import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "@playwright/test";

// Recorded real-event fixture (mirrors a live HN mi-mode run; CONTRACTS §7).
// Generated by `e2e/fixtures/generate-fixture.mjs`. Replaying it lets the whole
// dashboard be exercised end-to-end in CI with no GPU and no backend.
const REAL_RUN: Array<Record<string, unknown>> = JSON.parse(
  readFileSync(join(process.cwd(), "e2e/fixtures/real-run.json"), "utf-8"),
);

/**
 * Builds an init script that swaps `window.WebSocket` for a fake that streams
 * the recorded events with realistic per-event spacing. When `dropAt >= 0` the
 * socket closes once (simulating an engine restart) at that event index; the
 * hook then reconnects and the SAME cursor resumes — so accumulated state is
 * proven to survive a mid-run restart.
 */
function replayScript(
  events: Array<Record<string, unknown>>,
  stepMs: number,
  dropAt: number,
): string {
  return `
    (() => {
      const RealWS = window.WebSocket;
      const EVENTS = ${JSON.stringify(events)};
      const STEP = ${stepMs};
      const DROP_AT = ${dropAt};
      const run = (window.__run__ = window.__run__ || { cursor: 0, dropped: false });
      class FakeWS {
        constructor(url) {
          this.url = url;
          this.onopen = this.onclose = this.onerror = this.onmessage = null;
          this._timer = null;
          this._closed = false;
          setTimeout(() => {
            if (this._closed) return;
            if (this.onopen) this.onopen();
            this._pump();
          }, 20);
        }
        _pump() {
          if (this._closed) return;
          if (run.cursor >= EVENTS.length) return;
          if (DROP_AT >= 0 && !run.dropped && run.cursor === DROP_AT) {
            run.dropped = true;
            this._closed = true;
            if (this.onclose) this.onclose();
            return;
          }
          const ev = EVENTS[run.cursor++];
          if (this.onmessage) this.onmessage({ data: JSON.stringify(ev) });
          this._timer = setTimeout(() => this._pump(), STEP);
        }
        close() { this._closed = true; if (this._timer) clearTimeout(this._timer); }
      }
      window.WebSocket = function (url, protocols) {
        if (String(url).includes("/ws/events")) return new FakeWS(url);
        return new RealWS(url, protocols);
      };
    })();
  `;
}

/**
 * Self-contained smoke test: we replace window.WebSocket with a fake that
 * replays a canned CONTRACTS §7 sequence, so the test needs no backend.
 * Verifies all 4 panels render and layer bars light up within 2s of a
 * `layer_injection` event.
 */
const INIT_SCRIPT = `
  const RealWS = window.WebSocket;
  class FakeWS {
    constructor(url) {
      this.url = url;
      this.onopen = null; this.onclose = null;
      this.onerror = null; this.onmessage = null;
      setTimeout(() => {
        if (this.onopen) this.onopen();
        this._send({ type: "layer_injection", layers: [8,12,16,20], active: true, page_key: "hn:front", num_slots: 312 });
        this._send({ type: "viewport_frame", jpeg_base64: "/9j/4AAQSkZJRg==" });
        this._send({ type: "action", step: 1, action: { action: "goto", url: "https://news.ycombinator.com" } });
        this._send({ type: "token_metrics", session_id: "e2e", step: 1, mode: "mi", visible_tokens: 210, baseline_tokens: 1600, cum_visible: 210, cum_baseline: 1600, kv_savings_ratio: 7.6 });
        this._send({ type: "log", level: "info", message: "Bank hn:front injected at layers [8, 12, 16, 20]" });
      }, 50);
    }
    _send(obj) { if (this.onmessage) this.onmessage({ data: JSON.stringify(obj) }); }
    close() {}
  }
  // Only fake the inference feed; let Next.js HMR and others use the real socket.
  window.WebSocket = function (url, protocols) {
    if (String(url).includes("/ws/events")) return new FakeWS(url);
    return new RealWS(url, protocols);
  };
`;

test("renders 4 panels and lights up control layers from a layer_injection", async ({
  page,
}) => {
  await page.addInitScript(INIT_SCRIPT);
  await page.goto("/");

  await expect(page.getByText("LIVE VIEWPORT MIRROR")).toBeVisible();
  await expect(page.getByText("TOKEN COST COMPARATOR")).toBeVisible();
  await expect(page.getByText("LAYER INJECTION GRAPH")).toBeVisible();
  await expect(page.getByText("LOGS & MATH")).toBeVisible();

  // Control layers light up within 2s of the injection event.
  for (const layer of [8, 12, 16, 20]) {
    await expect(page.getByTestId(`layer-${layer}`)).toHaveAttribute(
      "data-lit",
      "true",
      { timeout: 2000 },
    );
  }

  // Session + mode propagate to the header.
  await expect(page.getByText("e2e")).toBeVisible();

  // Savings badge reflects the metric.
  await expect(page.getByTestId("savings-badge")).toContainText("7.6×");
});

test("renders a full recorded live run and captures a demo screenshot", async ({
  page,
}) => {
  await page.addInitScript(replayScript(REAL_RUN, 110, -1));
  await page.goto("/");

  // All four panels present.
  await expect(page.getByText("LIVE VIEWPORT MIRROR")).toBeVisible();
  await expect(page.getByText("TOKEN COST COMPARATOR")).toBeVisible();
  await expect(page.getByText("LAYER INJECTION GRAPH")).toBeVisible();
  await expect(page.getByText("LOGS & MATH")).toBeVisible();

  // Header binds to the live session/mode.
  await expect(page.getByText("mi-hn-live")).toBeVisible();

  // Control layers light up from the real layer_injection events.
  for (const layer of [8, 12, 16, 20]) {
    await expect(page.getByTestId(`layer-${layer}`)).toHaveAttribute(
      "data-lit",
      "true",
      { timeout: 5000 },
    );
  }

  // The unknown-page fallback moment: layers go dark on active:false.
  await expect
    .poll(() => page.getByTestId("layer-8").getAttribute("data-lit"), {
      timeout: 8000,
    })
    .toBe("false");

  // Two diverging series are charted.
  await expect(page.getByText("Standard prompting")).toBeVisible();
  await expect(page.getByText("GhostBrowser MI")).toBeVisible();

  // Wait for the run to complete so the screenshot shows a fully populated state.
  await expect(page.getByText("Task complete")).toBeVisible({ timeout: 12000 });

  // The math panel reflects real num_slots and DOM token count.
  await expect(page.getByTestId("num-slots")).toContainText("240");
  await expect(page.getByTestId("dom-token-count")).toContainText("13,900");

  // Cumulative savings settled to an order-of-magnitude win.
  await expect(page.getByTestId("savings-badge")).toContainText("11.5×");

  // Let the ratio ticker + chart settle, then capture the demo still.
  // Hide the Next.js dev-tools indicator so the still is clean for slides.
  await page.addStyleTag({
    content: "nextjs-portal{display:none !important;}",
  });
  await page.waitForTimeout(1200);
  await page.screenshot({
    path: join(
      process.cwd(),
      "../../docs/handoff/phase-2/notes/p4-console-shot.png",
    ),
    fullPage: false,
  });
});

test("survives an engine restart mid-run and shows a reconnecting state", async ({
  page,
}) => {
  // Drop the socket at the 3rd step's first event (index 10 = 2 steps × 5 events).
  await page.addInitScript(replayScript(REAL_RUN, 90, 10));
  await page.goto("/");

  // First two steps stream in.
  await expect(page.getByText("mi-hn-live")).toBeVisible();
  await expect(page.getByTestId("savings-badge")).toContainText("67.1×", {
    timeout: 8000,
  });

  // Engine restart: a clear reconnecting banner appears (not a frozen panel).
  await expect(page.getByTestId("reconnect-banner")).toBeVisible({
    timeout: 5000,
  });
  // Accumulated state is preserved while disconnected.
  await expect(page.getByTestId("savings-badge")).toContainText("67.1×");

  // After backoff the feed reconnects, the banner clears, and the run finishes.
  await expect(page.getByTestId("reconnect-banner")).toBeHidden({
    timeout: 8000,
  });
  await expect(page.getByText("Task complete")).toBeVisible({ timeout: 12000 });
  await expect(page.getByTestId("savings-badge")).toContainText("11.5×");
});
