"""B2 spec, unit test #3: every stored .bin file's byte length must equal
8 * num_slots * 128 * 4 (NUM_KV_HEADS * S * HEAD_DIM * sizeof(float32)).

This is the invariant the engine relies on at load time. If any compiled bank
violates it, the in-memory dict at the inference engine will reshape wrong
and silently produce garbage attention output.

Runs against whatever banks/manifest.json + .bin files are present locally
(generated by `python scripts/build_demo_banks.py` or by B1's real compiler).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

from ghost_shared import bank_io
from ghost_shared.constants import HEAD_DIM, NUM_KV_HEADS, SELECTED_LAYERS

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BANKS_DIR = REPO_ROOT / "banks"
F32_BYTES = 4
EXPECTED_BYTES_PER_SLOT = NUM_KV_HEADS * HEAD_DIM * F32_BYTES  # 4096


@pytest.fixture(scope="module")
def banks_dir(tmp_path_factory) -> Path:
    """Use the repo's banks/ if it has .bin files; else build a temp set."""
    repo_dir = DEFAULT_BANKS_DIR
    if repo_dir.exists() and any(repo_dir.glob("*.bin")):
        return repo_dir

    tmp_dir = tmp_path_factory.mktemp("banks")
    subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "build_demo_banks.py"),
            "--force-synthetic",
            "--out",
            str(tmp_dir),
        ],
        check=True,
        cwd=str(REPO_ROOT),
    )
    return tmp_dir


def test_manifest_lists_three_banks(banks_dir):
    manifest = bank_io.read_manifest(str(banks_dir))
    assert manifest["selected_layers"] == SELECTED_LAYERS
    page_keys = {e["page_key"] for e in manifest["banks"]}
    assert page_keys == {"hn:front", "hn:item", "popup:demo"}


def test_byte_length_invariant(banks_dir):
    """For every (page_key, layer, k|v): file size == 8 * S * 128 * 4."""
    manifest = bank_io.read_manifest(str(banks_dir))
    assert manifest["banks"], "manifest has no banks"

    for entry in manifest["banks"]:
        num_slots = int(entry["num_slots"])
        expected = num_slots * EXPECTED_BYTES_PER_SLOT
        for layer_str, files in entry["files"].items():
            for kind in ("k", "v"):
                path = banks_dir / files[kind]
                assert path.exists(), f"missing bin: {path}"
                size = os.path.getsize(path)
                assert size == expected, (
                    f"{path.name}: size {size} != expected {expected} "
                    f"(num_slots={num_slots}, layer={layer_str})"
                )


def test_loaded_shape_and_dtype(banks_dir):
    """bank_io.load_bank returns the contracted [8, S, 128] float32 arrays."""
    manifest = bank_io.read_manifest(str(banks_dir))
    for entry in manifest["banks"]:
        loaded = bank_io.load_bank(entry, str(banks_dir))
        assert sorted(loaded.keys()) == sorted(SELECTED_LAYERS)
        S = int(entry["num_slots"])
        for layer, (k, v) in loaded.items():
            assert k.shape == (NUM_KV_HEADS, S, HEAD_DIM), (layer, k.shape)
            assert v.shape == (NUM_KV_HEADS, S, HEAD_DIM), (layer, v.shape)
            assert str(k.dtype) == "float32"
            assert str(v.dtype) == "float32"


def test_num_slots_identical_across_layers(banks_dir):
    """CONTRACTS §4: num_slots is identical across the 4 layers within one bank."""
    manifest = bank_io.read_manifest(str(banks_dir))
    for entry in manifest["banks"]:
        loaded = bank_io.load_bank(entry, str(banks_dir))
        slot_counts = {k.shape[1] for k, _ in loaded.values()}
        assert len(slot_counts) == 1, (
            f"{entry['page_key']}: layers disagree on num_slots: {slot_counts}"
        )


def test_summary_files_exist_and_nonempty(banks_dir):
    manifest = bank_io.read_manifest(str(banks_dir))
    for entry in manifest["banks"]:
        rel = entry.get("summary_text_path", "")
        assert rel, f"{entry['page_key']}: missing summary_text_path"
        candidates = [
            REPO_ROOT / rel,
            banks_dir / Path(rel).name,
        ]
        path = next((c for c in candidates if c.exists()), None)
        assert path is not None, f"summary not found for {entry['page_key']}: {rel}"
        assert path.read_text(encoding="utf-8").strip(), (
            f"summary empty for {entry['page_key']}"
        )
